<?php

/**
 * @file
 * Contains country_details_app.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function country_details_app_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the country_details_app module.
    case 'help.page.country_details_app':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Country Details App') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function country_details_app_theme() {
  return [
    'country_details_app' => [
      'render element' => 'children',
    ],
  ];
}
