/**
 * DO NOT EDIT THIS FILE.
 * See the following change record for more information,
 * https://www.drupal.org/node/2815083
 * @preserve
 **/
CKEDITOR.plugins.add("div", {
  init: function (editor) {
    if (editor.ui.addButton) {
      editor.ui.addButton("CreateDiv", {
        label: "default ckeditor button",
        id: "div",
        command: "",
        toolbar: "CreateDiv,10",
      });
    }
  },
});
